--->Multiple linear Regression((o/p) multiple parmeter depend kare)
y=m1x1+m2x2+m3x3+m4x4+m4x5+c

step1 read csv file
step2 null value find karo
step3 add new columns data pre-processing
step4 all data convert into numerical and boolean form 
step5 x and y defined and split into train and test
step6 model banvisu
step7 ane jem value aapi hoy te rite value prdict karvani
step8 MSE find

In [18]:
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

In [19]:
#step1
df=pd.read_csv("car data.csv")
df.head()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0


In [20]:
#step2
df.isna().sum()

Car_Name         0
Year             0
Selling_Price    0
Present_Price    0
Kms_Driven       0
Fuel_Type        0
Seller_Type      0
Transmission     0
Owner            0
dtype: int64

In [21]:
#step3 data pre-processing
df["Age"]=2026-df["Year"]
df.head()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner,Age
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0,12
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0,13
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0,9
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0,15
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0,12


In [25]:
#drop Year columns because dosen't require 
df.drop(columns='Year',inplace=True)


In [23]:
df.drop(columns='Car_Name',inplace=True)


In [26]:
df

,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner,Age
0,3.35,5.59,27000,Petrol,Dealer,Manual,0,12
1,4.75,9.54,43000,Diesel,Dealer,Manual,0,13
2,7.25,9.85,6900,Petrol,Dealer,Manual,0,9
3,2.85,4.15,5200,Petrol,Dealer,Manual,0,15
4,4.60,6.87,42450,Diesel,Dealer,Manual,0,12
...,...,...,...,...,...,...,...,...
296,9.50,11.60,33988,Diesel,Dealer,Manual,0,10
297,4.00,5.90,60000,Petrol,Dealer,Manual,0,11
298,3.35,11.00,87934,Petrol,Dealer,Manual,0,17
299,11.50,12.50,9000,Diesel,Dealer,Manual,0,9


In [27]:
df=pd.get_dummies(data=df,drop_first=True)#drop_first actual columns delete kari de 
df

,Selling_Price,Present_Price,Kms_Driven,Owner,Age,Fuel_Type_Diesel,Fuel_Type_Petrol,Seller_Type_Individual,Transmission_Manual
0,3.35,5.59,27000,0,12,False,True,False,True
1,4.75,9.54,43000,0,13,True,False,False,True
2,7.25,9.85,6900,0,9,False,True,False,True
3,2.85,4.15,5200,0,15,False,True,False,True
4,4.60,6.87,42450,0,12,True,False,False,True
...,...,...,...,...,...,...,...,...,...
296,9.50,11.60,33988,0,10,True,False,False,True
297,4.00,5.90,60000,0,11,False,True,False,True
298,3.35,11.00,87934,0,17,False,True,False,True
299,11.50,12.50,9000,0,9,True,False,False,True


In [31]:
y=df["Selling_Price"]
x=df[['Present_Price', 'Kms_Driven', 'Owner', 'Age',
       'Fuel_Type_Diesel', 'Fuel_Type_Petrol', 'Seller_Type_Individual',
       'Transmission_Manual']]

In [29]:
df.columns

Index(['Selling_Price', 'Present_Price', 'Kms_Driven', 'Owner', 'Age',
       'Fuel_Type_Diesel', 'Fuel_Type_Petrol', 'Seller_Type_Individual',
       'Transmission_Manual'],
      dtype='object')

In [33]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
print(x_train.shape)#2 dimnesion
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(240, 8)
(61, 8)
(240,)
(61,)


In [36]:
from sklearn.linear_model import LinearRegression
lr= LinearRegression()
lr.fit(x_train,y_train)#modal bani gayu

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [38]:
m=lr.coef_#  amaa total 8 columns che etla 8 o/p aavyu etla y=m1x1+m2x2+m3x3+m4x4+m5x5+...+m8x8+c
m

array([ 4.29152503e-01, -6.15725866e-06, -9.03759824e-01, -3.53801365e-01,
        2.53327258e+00,  7.38464226e-01, -1.19059291e+00, -1.63902155e+00])

In [40]:
c=lr.intercept_
c

np.float64(6.848642647119785)

In [54]:
#i20 car /8year old /petrol/manual/45000km/owner 0/8.5lakh/indivisual
i20_price=lr.predict(df[['Present_Price', 'Kms_Driven', 'Owner', 'Age',
       'Fuel_Type_Diesel', 'Fuel_Type_Petrol', 'Seller_Type_Individual',
       'Transmission_Manual']])

In [53]:
#i20 car /8year old /petrol/manual/45000km/owner 0/8.5lakh/indivisual
i20_price=lr.predict([[8.5,45000,0,8,0,1,1,1]])#olumns maa jem data hoy tem naakho
i20_price

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([5.29780112])

In [55]:
#modeal ketlu accurate ketlo che e check karva ketli error che e shodhva mate 

#aama 3 columns genrate thase x_test(value predict karva mate ni columns) /y_test(actual value of car)/y_pred(model) (car ni value predicat kare)

y_pred=lr.predict(x_test)#predict kari ne aapiyo answer package 
y_pred

from sklearn.metrics import mean_squared_error
print("MSE=",mean_squared_error(y_test,y_pred))

MSE= 3.478803970637871


In [58]:
#new code

#-->vine quality
import pandas as pd
import numpy as np

df=pd.read_csv("winequality.csv")
df.head(5)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,1
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,2
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,3
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,4


In [59]:
df.isna().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
Id                      0
dtype: int64

In [61]:
df.drop(columns="Id",inplace=True)


In [62]:
df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1138,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1139,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6
1140,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1141,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6


In [63]:
df=pd.get_dummies(data=df,drop_first=True)#drop_first actual columns delete kari de 
df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1138,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1139,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6
1140,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1141,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6


In [66]:
y=df["quality"]
x=df[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol']]

In [65]:
df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [67]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
print(x_train.shape)#2 dimnesion
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(914, 11)
(229, 11)
(914,)
(229,)


In [71]:
from sklearn.linear_model import LinearRegression
lr= LinearRegression()
lr.fit(x_train,y_train)#modal bani gayu

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [76]:
m=lr.coef_#  amaa total 8 columns che etla 8 o/p aavyu etla y=m1x1+m2x2+m3x3+m4x4+m5x5+...+m8x8+c
m

array([ 5.13430654e-02, -1.33625691e+00, -3.39100758e-01,  4.12143173e-03,
       -1.80653035e+00,  1.88076181e-03, -2.28305818e-03, -3.06532562e+01,
       -2.49236344e-01,  9.73040097e-01,  2.66586068e-01])

In [77]:
c=lr.intercept_
c

np.float64(34.209805578378685)

In [78]:
vine_quality=lr.predict(df[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol']])

In [74]:
vine_quality=lr.predict([[8,0.4,0.40,15,0.048,40,150,0.99,3,0.45,10.5]])
vine_quality

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([5.80087585])

In [79]:
vine_quality=lr.predict([[8,0.4,0.40,15,0.048,40,150,0.99,3,0.45,10.5]])
vine_quality

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([5.80087585])

In [75]:
y_pred=lr.predict(x_test)#predict kari ne aapiyo answer package 
y_pred

from sklearn.metrics import mean_squared_error
print("MSE=",mean_squared_error(y_test,y_pred))

MSE= 0.38003245026277577


In [14]:
import pandas as pd
import numpy as np

df=pd.read_csv("RealEstate.csv")
df.head(5)

,No,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
0,1,2012.917,32.0,84.87882,10,24.98298,121.54024,37.9
1,2,2012.917,19.5,306.59470,9,24.98034,121.53951,42.2
2,3,2013.583,13.3,561.98450,5,24.98746,121.54391,47.3
3,4,2013.500,13.3,561.98450,5,24.98746,121.54391,54.8
4,5,2012.833,5.0,390.56840,5,24.97937,121.54245,43.1


In [15]:
df.isna().sum()

No                                        0
X1 transaction date                       0
X2 house age                              0
X3 distance to the nearest MRT station    0
X4 number of convenience stores           0
X5 latitude                               0
X6 longitude                              0
Y house price of unit area                0
dtype: int64

In [16]:
df.drop(columns="No",inplace=True)

In [17]:
df=pd.get_dummies(data=df,drop_first=True)#drop_first actual columns delete kari de 
df

,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
0,2012.917,32.0,84.87882,10,24.98298,121.54024,37.9
1,2012.917,19.5,306.59470,9,24.98034,121.53951,42.2
2,2013.583,13.3,561.98450,5,24.98746,121.54391,47.3
3,2013.500,13.3,561.98450,5,24.98746,121.54391,54.8
4,2012.833,5.0,390.56840,5,24.97937,121.54245,43.1
...,...,...,...,...,...,...,...
409,2013.000,13.7,4082.01500,0,24.94155,121.50381,15.4
410,2012.667,5.6,90.45606,9,24.97433,121.54310,50.0
411,2013.250,18.8,390.96960,7,24.97923,121.53986,40.6
412,2013.000,8.1,104.81010,5,24.96674,121.54067,52.5


In [18]:
y=df["Y house price of unit area"]
x=df[['X1 transaction date', 'X2 house age',
       'X3 distance to the nearest MRT station',
       'X4 number of convenience stores', 'X5 latitude', 'X6 longitude',]]

In [19]:
df.columns

Index(['X1 transaction date', 'X2 house age',
       'X3 distance to the nearest MRT station',
       'X4 number of convenience stores', 'X5 latitude', 'X6 longitude',
       'Y house price of unit area'],
      dtype='object')

In [20]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=110)
print(x_train.shape)#2 dimnesion
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(289, 6)
(125, 6)
(289,)
(125,)


In [21]:
from sklearn.linear_model import LinearRegression
lr= LinearRegression()
lr.fit(x_train,y_train)#modal bani gayu

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [22]:
m=lr.coef_#  amaa total 8 columns che etla 8 o/p aavyu etla y=m1x1+m2x2+m3x3+m4x4+m5x5+...+m8x8+c
m

array([ 6.84308941e+00, -2.25466590e-01, -5.18046265e-03,  1.12369103e+00,
        1.87739728e+02, -4.29300312e+01])

In [23]:
c=lr.intercept_
c

np.float64(-13203.674300629997)

In [24]:
predict=lr.predict(df[['X1 transaction date', 'X2 house age',
       'X3 distance to the nearest MRT station',
       'X4 number of convenience stores', 'X5 latitude', 'X6 longitude',]])
predict

array([47.05055734, 47.13231389, 48.41771758, 47.84974116, 44.58865137,
       29.70762483, 38.09362058, 46.99690361,  9.25548578, 35.13504057,
       34.28075691, 52.79246165, 40.38150293, 26.02581541, 44.81813044,
       38.85912213, 49.74492584, 36.61381207, 47.07233847, 46.26562684,
       34.96483541, 49.2744848 , 28.0716375 , 47.07907957, 35.39784888,
       32.10482846, 44.13100218, 42.55779983, 43.1828412 , 44.61671482,
       13.59062281, 39.76418735, 30.83730724, 46.12400232, 45.7883975 ,
       30.07290031, 29.88907181, 30.39116965, 42.44745248, 45.32867586,
       13.60907813, 16.67238705, 38.0504346 , 39.3810272 , 47.22860641,
       40.19891138, 47.14003299, 38.73605135, 12.69738744,  8.47840703,
       42.2289638 , 23.58447015, 36.03287449, 41.44981579, 44.77640301,
       23.9175752 , 44.40541255, 45.59192922, 13.97578058, 40.99985481,
       34.11953277, 50.11002128, 29.13304197, 47.25115307, 33.08671633,
       44.82145569, 46.27991859, 47.54948183, 43.83987219, 43.46

In [25]:
y_pred=lr.predict(x_test)#predict kari ne aapiyo answer package 
y_pred

from sklearn.metrics import mean_squared_error
print("MSE=",mean_squared_error(y_test,y_pred))

MSE= 77.14802598253598


In [26]:

from sklearn.metrics import mean_absolute_error
mae=mean_absolute_error(y_pred,y_test)
print("MAE=",mae)

MAE= 6.443245493782295


In [28]:
from sklearn.metrics import mean_squared_error
mae=mean_squared_error(y_pred,y_test)
print("MAE=",mae)

MAE= 77.14802598253598


In [29]:
from sklearn.metrics import r2_score
mae=r2_score(y_pred,y_test)
print("MAE=",mae)

MAE= 0.22374403332184478
